### ISSUE TITLE
Limpeza dos datasets

### ISSUE THREAD

**Issue by LuisandradeA** [nandomaciel/Fast-Obesity#1]
Criar notebook para limpeza dos dados

**Comment by EulleSA** [comment]
Arquivo FastFoods -->

Retirar as colunas :: "address" , "country" , "keys" , "postalCode" , "websites"

Mudar o nome "província" para "state"

**Comment by nandomaciel** [comment]
Os datasets foram limpos de modo que somente as colunas necessárias para o trabalho foram utilizadas.
